const allData = [
  // men
  {
    id: "1",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/z/z/h/xl-battle-beast-mens-printed-oversized-t-shirt-battlebeast-original-imah4c2twys4stdg.jpeg?q=70",
    name: "Puma",
    price: 679,
    description: "Ess Polo T-shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "2",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/j/b/q/-original-imagy3k8xjfjhm4d.jpeg?q=70",
    name: "Puma",
    price: 1034,
    description: "Men Medium Grey Solid ESS Jersey Pants",
    qty: 1,
    category: "Men",
  },
  {
    id: "3",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/e/b/t/m-t-26-1st-bukkl-original-imah3jdkrk8mmfsb.jpeg?q=70",
    name: "BUKKL",
    price: 289,
    description: "Men Printed Round Neck Pure Cotton White T-Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "4",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/k/v/m/xl-ts12-vebnor-original-imahfbc3yfnxp9j9.jpeg?q=70",
    name: "VeBNoR",
    price: 349,
    description: "Men Printed Round Neck Polyester Light Green T-Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "5",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/r/z/l/s-gucci-tshirt-sti-original-imahyyzs4kpgbfby.jpeg?q=70",
    name: "sti",
    price: 179,
    description: "Men Printed Round Neck Polyester White, Black T-Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "6",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/e/p/k/xl-sht02-ethvil-original-imagruyhhgztm4hj.jpeg?q=70",
    name: "Plorviz",
    price: 300,
    description: "Men Regular Fit Solid Mandarin Collar Casual Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "7",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/d/7/t/l-fms-182-fllseve-pop-wt-force-original-imah3qahwggdvdgm.jpeg?q=70",
    name: "Force",
    price: 339,
    description: "Men Regular Fit Solid Curved Collar Casual Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "8",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/e/y/h/m-towel-001-tallwalker-original-imaghct3gemhajg5.jpeg?q=70",
    name: "VASTRADO",
    price: 849,
    description: "Men Slim Fit Solid Lapel Collar Casual Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "9",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/5/7/v/3xl-formal-shirt-metronaut-original-imah2hqncjyyqead.jpeg?q=70",
    name: "VeBNoR ",
    price: 299,
    description:
      "Men Regular Fit Solid Button Down Collar Formal Shirt#JustHere",
    qty: 1,
    category: "Men",
  },
  {
    id: "10",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/2/s/e/s-rt121-s-line-original-imah3d3v9muqqeh4.jpeg?q=70",
    name: "S-Line",
    price: 299,
    description: "Men Regular Fit Printed Mandarin Collar Casual Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "11",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/r/c/4/s-jawan-one-nb-nicky-boy-original-imahfyq24y3hamvg.jpeg?q=70",
    name: "NB NICKY BOY",
    price: 249,
    description: "Men Printed Round Neck Cotton Blend Black T-Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "12",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/e/4/4/m-t599-whbl-eyebogler-original-imah46h9vwtyzkr8.jpeg?q=70",
    name: "EyeBogler",
    price: 269,
    description: "Men Checkered Hooded Neck Cotton Blend White T-Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "13",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/g/f/o/xxl-tblrnful-d158-tripr-original-imah545thkfje4sm.jpeg?q=70",
    name: "TRIPR",
    price: 259,
    description: "Men Solid V Neck Cotton Blend Black T-Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "14",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/g/a/t/l-hood-263-nasa-black-lewel-original-imaggeft89kbgsnh.jpeg?q=70",
    name: "LEWEL",
    price: 259,
    description: "Men Typography Hooded Neck Cotton Blend White, Black T-Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "15",
    img: "https://rukminim2.flixcart.com/image/612/612/l41n2q80/t-shirt/7/o/1/m-1jgrf-013-must-jugular-original-imagff7wwu2ptt9y.jpeg?q=70",
    name: "JUGULAR",
    price: 459,
    description: "Men Printed Round Neck Pure Cotton Yellow T-Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "16",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/7/v/0/l-t3-t2-autna-original-imagqphp3hj6vqdj.jpeg?q=70",
    name: "Autna",
    price: 659,
    description:
      "Men Colorblock V Neck Cotton Blend Maroon, Black, White T-Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "17",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/q/h/z/xl-jc23-polo-fs-olive-california-jump-cuts-original-imagvh7g6axuvyug.jpeg?q=70",
    name: "Jump Cuts",
    price: 999,
    description: "Men Printed Polo Neck Cotton Blend Dark Green T-Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "18",
    img: "https://rukminim2.flixcart.com/image/300/300/xif0q/t-shirt/i/q/b/m-white-black-pink-kroptee-original-imagkrk4gg4aatzm.jpeg?q=90",
    name: "Kroptee",
    price: 1199,
    description: "Men Colorblock Round Neck Pure Cotton Pink T-Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "19",
    img: "https://rukminim2.flixcart.com/image/300/300/xif0q/t-shirt/4/t/i/xxl-ausk0179-ausk-original-imagmffbcvcxu9gf.jpeg?q=90",
    name: "AUSK",
    price: 529,
    description:
      "Men Colorblock Polo Neck Cotton Blend Beige, Black, White T-Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "20",
    img: "https://rukminim2.flixcart.com/image/612/612/kjhgzgw0-0/t-shirt/9/x/l/l-12329170-wrogn-original-imafzfb88duhmwz3.jpeg?q=70",
    name: "WROGN",
    price: 899,
    description: "Men Striped Round Neck Pure Cotton White T-Shirt",
    qty: 1,
    category: "Men",
  },

  //   women

  {
    id: "21",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/fabric/i/j/t/yes-2-m-unstitched-2-m-2-5-m-ti-1503-inithi-original-imah2axgyydpyhev.jpeg?q=70",
    name: "THIRA",
    price: 249,
    description: "Unstitched Crepe Salwar Suit Material Printed",
    qty: 1,
    category: "Women",
  },
  {
    id: "22",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/fabric/e/4/h/yes-2-m-unstitched-2-m-2-5-m-1576-laxmi-creation-original-imah29sfxaamgnna.jpeg?q=70",
    name: "THIRA",
    price: 249,
    description: "Unstitched Crepe Salwar Suit Material Printed",
    qty: 1,
    category: "Women",
  },
  {
    id: "23",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/fabric/5/z/t/yes-2-m-unstitched-2-m-2-5-m-ti-1567-inithi-original-imah2axgsa5vcg3y.jpeg?q=70",
    name: "THIRA",
    price: 249,
    description: "Unstitched Crepe Salwar Suit Material Printed",
    qty: 1,
    category: "Women",
  },
  {
    id: "24",
    img: "https://rukminim2.flixcart.com/image/612/612/l51d30w0/dress/n/g/n/xxl-d515-dress-s-starword-original-imagfsw6ynqpje7f.jpeg?q=70",
    name: "starword",
    price: 379,
    description: "Women Pleated Blue Dress",
    qty: 1,
    category: "Women",
  },
  {
    id: "25",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/dress/d/a/e/xl-f-188-190-sumertex-original-imagj3p5fhvvtcmt.jpeg?q=70",
    name: "METRONAUT",
    price: 319,
    description: "Women Fit and Flare Maroon Dress",
    qty: 1,
    category: "Women",
  },
  {
    id: "26",
    img: "https://rukminim2.flixcart.com/image/612/612/l1pc3gw0/dress/x/w/n/l-159-167-sumertex-original-imagd7hzdg2zzyau.jpeg?q=70",
    name: "SUMERTEX",
    price: 999,
    description: "Women Fit and Flare Brown Dress",
    qty: 1,
    category: "Women",
  },

  {
    id: "27",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/dress/r/j/u/m-dresses-lakshya-fashion-mart-original-imah2wymga5bfghz.jpeg?q=70",
    name: "Lakshya Fashion Mart",
    price: 239,
    description: "Women Fit and Flare Multicolor Dress",
    qty: 1,
    category: "Women",
  },
  {
    id: "28",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/dress/i/d/r/6xl-velvet-f-44-garima-fashion-original-imagnhzwtzpwufut.jpeg?q=70",
    name: "Garima Fashion",
    price: 3289,
    description: "Women Fit and Flare Maroon Dress",
    qty: 1,
    category: "Women",
  },
  {
    id: "29",
    img: "https://rukminim2.flixcart.com/image/612/612/k62i5jk0/dress/x/n/k/xl-fr-6022-gorangani-original-imafkyczeq7qvkzf.jpeg?q=70",
    name: "maruti fab",
    price: 7289,
    description: "Women Fit and Flare Black, Beige, Brown Dress",
    qty: 1,
    category: "Women",
  },
  {
    id: "30",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/dress/x/b/8/l-131923901-vero-moda-original-imagu8t6ymysp2r9.jpeg?q=70",
    name: "VERO MODA",
    price: 4299,
    description: "Women Fit and Flare Black Dress",
    qty: 1,
    category: "Women",
  },
  {
    id: "31",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/dress/b/0/u/s-rr-403-emb-frock-lozzby-original-imaghkupbfdtu5yk.jpeg?q=70",
    name: "BRIGHT WORLD",
    price: 399,
    description: "Women Ethnic Dress Black Dress",
    qty: 1,
    category: "Women",
  },
  {
    id: "32",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/dress/9/b/2/m-flared-dress-iqra-enterprise-original-imah28hguqqnbxpa.jpeg?q=70",
    name: "IQRA ENTERPRISE",
    price: 3909,
    description: "Women Fit and Flare Green Dress",
    qty: 1,
    category: "Women",
  },
  {
    id: "33",
    img: "https://rukminim2.flixcart.com/image/612/612/kjg1jm80-0/kurta/u/j/v/m-frock-10-gg-fashion-original-imafzy9tdxugehbe.jpeg?q=70",
    name: "Jashudi Style",
    price: 403,
    description: "Women A-line Black Dress",
    qty: 1,
    category: "Women",
  },
  {
    id: "34",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/dress/i/w/v/m-shirt-dress-black-plain-klart-original-imah4ebzhfvvegq6.jpeg?q=70",
    name: "KLART",
    price: 403,
    description: "Women Shirt Black Dress",
    qty: 1,
    category: "Women",
  },
  {
    id: "35",
    img: "https://rukminim2.flixcart.com/image/612/612/l1jmc280/dress/n/h/e/l-168-176-sumertex-original-imagd3a6zhayhszx.jpeg?q=70",
    name: "SUMERTEX",
    price: 807,
    description: "Women Fit and Flare Green Dress",
    qty: 1,
    category: "Women",
  },
  {
    id: "36",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/dress/l/n/e/m-women-s-crepe-knee-length-frock-dress-nyty20-original-imahfhvzgqqf3gsw.jpeg?q=70",
    name: "NYTY20",
    price: 535,
    description: "Women Fit and Flare Black Dress",
    qty: 1,
    category: "Women",
  },

  {
    id: "37",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/fabric/4/z/u/yes-2-m-unstitched-2-10m-jsg1618-simplyenthic-original-imagw9f4gy7z8epm.jpeg?q=70",
    name: "SIMPLYENTHIC",
    price: 279,
    description: "Unstitched Crepe Kurta & Churidar Material Printed",
    qty: 1,
    category: "Women",
  },
  {
    id: "38",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/fabric/n/k/x/yes-2-2-m-unstitched-2-10m-jsg1396-simplyethnic-original-imahftgdq49fpzxe.jpeg?q=70",
    name: "SIMPLYENTHIC",
    price: 674,
    description: "Unstitched Crepe Kurta & Churidar Material Printed",
    qty: 1,
    category: "Women",
  },
  {
    id: "39",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/fabric/r/e/6/yes-2-2-m-unstitched-2-m-2-5-m-free-7777888-amaaya-fashion-original-imah2txkhezsvmve.jpeg?q=70",
    name: "amaaya fashion",
    price: 674,
    description: "Unstitched Crepe Salwar Suit Material Printed",
    qty: 1,
    category: "Women",
  },

  {
    id: "40",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/jacket/f/b/v/s-1-no-lady-jacket-printcorners-original-imah4n8q6efczndg.jpeg?q=70",
    name: "printcorners",
    price: 674,
    description: "Women Solid Leather Jacket",
    qty: 1,
    category: "Women",
  },

  //   kids

  {
    id: "41",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/g/s/p/4-5-years-cpby0037-carrydreams-original-imagksy3yundy6bz.jpeg?q=70",
    name: "CHANDRIKA LIFESTYLE",
    price: 270,
    description: "Boys Party(Festive) T-shirt Trouser  (MEHENDI)",
    qty: 1,
    category: "boys",
  },
  {
    id: "42",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/t/4/y/6-7-years-ctcn01-cute-n-tight-original-imagsdfvnsfzrdp2.jpeg?q=70",
    name: "PY PINKYOU",
    price: 400,
    description: "Boys Casual Sweatshirt Track Pants  (Black)",
    qty: 1,
    category: "boys",
  },
  {
    id: "43",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shopsy-kids-apparel-combo/z/k/1/1-2-years-cpby0032-shopsy-chandrika-lifestyle-original-imagkrv3y2b7gprs.jpeg?q=70",
    name: "CHANDRIKA LIFESTYLE",
    price: 799,
    description: "Boys Casual Pants (Black)",
    qty: 1,
    category: "boys",
  },
  {
    id: "44",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/k/k/q/7-8-years-black-open-denim-blue-bold-born-original-imah375yrhgcwdeg.jpeg?q=70",
    name: "Bold Born",
    price: 499,
    description: "Boys Party(Festive) Shirt Jacket, Jeans (Blue)",
    qty: 1,
    category: "boys",
  },
  {
    id: "45",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/u/f/j/4-5-years-f1aa-lxri-original-imagpzyrgzrhrwg4.jpeg?q=70",
    name: "Lxri",
    price: 799,
    description: "Boys Party(Festive) Shirt Pant, Waistcoat  (Green)",
    qty: 1,
    category: "boys",
  },
  {
    id: "46",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/m/a/l/6-7-years-babushona636-yellow-30-babushona-original-imah3fgfjcsvg6qf.jpeg?q=70",
    name: "BABUSHONA",
    price: 699,
    description: "Boys Party(Festive) Track Pants Shirt  (Yellow)",
    qty: 1,
    category: "boys",
  },
  {
    id: "47",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/x/b/r/2-3-years-sp-6-year-grey-ultrina-original-imagqfucnktutw7c.jpeg?q=70",
    name: "ULTRINA",
    price: 369,
    description:
      "Boys Party(Festive) Shirt Pant, Bow Tie, Suspenders  (SKY BLUE)",
    qty: 1,
    category: "boys",
  },
  {
    id: "48",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shopsy-kid-costume-wear/x/t/b/72-4-5-years-cpby001-shopsy-pol-chandrika-lifestyle-84-original-imaghh3xtw63gqmm.jpeg?q=70",
    name: "ULTRINA",
    price: 325,
    description: "Chandrika Police Dress",
    qty: 1,
    category: "boys",
  },
  {
    id: "49",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/p/i/v/11-12-years-denc01-druzzee-original-imagwnkr3rjg8ags.jpeg?q=70",
    name: "DRUZZEE",
    price: 270,
    description: "Boys Casual T-shirt Track Pants  (Navy)",
    qty: 1,
    category: "boys",
  },
  {
    id: "50",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kid-costume-wear/z/9/p/2-3-years-military-costume-for-kids-kenim-fashion-original-imagvn5t3ugyq6vb.jpeg?q=70",
    name: "DRUZZEE",
    price: 270,
    description: "Chandrika Army Dress",
    qty: 1,
    category: "boys",
  },
  {
    id: "51",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/u/5/m/7-8-years-phd-go-berry-original-imah2mfv4rrcyywc.jpeg?q=70",
    name: "Go Berry",
    price: 644,
    description: "Boys Party(Festive) Shirt Pant  (YELLOW)",
    qty: 1,
    category: "boys",
  },
  {
    id: "52",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/x/y/j/1-2-years-trm-ttp-130-trampoline-original-imah5vsugnv3p7gf.jpeg?q=70",
    name: "Trampoline",
    price: 747,
    description: "Boys Casual T-shirt Track Pants  (Black, Blue)",
    qty: 1,
    category: "boys",
  },
  {
    id: "53",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/b/z/z/7-8-years-55-coat-go-berry-original-imah2m2f9en4qmae.jpeg?q=70",
    name: "Go Berry",
    price: 489,
    description: "Boys Party(Festive) Shirt Pant  (BLUE)",
    qty: 1,
    category: "boys",
  },
  {
    id: "54",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/g/v/9/3-4-years-army-printed-track-pant-t-shirt-set-for-boys-6-dollico-original-imahy9mjeeugrfhb.jpeg?q=70",
    name: "Kilimoli",
    price: 491,
    description: "Boys Party(Festive) Track Pants T-shirt  (White)",
    qty: 1,
    category: "boys",
  },
  {
    id: "55",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/k/x/o/4-5-years-open-black-double-pocket-blue-good-doo-apparel-s-original-imaggf6ruaudv96m.jpeg?q=70",
    name: "Kilimoli",
    price: 491,
    description: "Boys Party(Festive) Track Pants T-shirt  (White)",
    qty: 1,
    category: "boys",
  },
  {
    id: "56",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/m/u/p/3-4-years-dior-hood-red-mini-tikes-original-imah2guyvksrru6s.jpeg?q=70",
    name: "Kilimoli",
    price: 491,
    description: "Boys Party(Festive) Track Pants T-shirt  (White)",
    qty: 1,
    category: "boys",
  },
  {
    id: "57",
    img: "https://rukminim2.flixcart.com/image/612/612/kqgyhe80/kids-apparel-combo/s/l/j/12-13-years-3-pc-320-blue-zolario-original-imag4h9ycd5tsswg.jpeg?q=70",
    name: "Kilimoli",
    price: 491,
    description: "Boys Party(Festive) Track Pants T-shirt  (White)",
    qty: 1,
    category: "boys",
  },
  {
    id: "58",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/e/x/4/11-12-years-homtom-oversize-t-viskri-original-imagyp4dgfa2aes4.jpeg?q=70",
    name: "Kilimoli",
    price: 491,
    description: "Boys Party(Festive) Track Pants T-shirt  (White)",
    qty: 1,
    category: "boys",
  },
  {
    id: "59",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/u/l/m/8-9-years-boys-t-shirts-with-track-pant-ninos-dreams-original-imagxz4tyhfkfmup.jpeg?q=70",
    name: "Kilimoli",
    price: 491,
    description: "Boys Party(Festive) Track Pants T-shirt  (White)",
    qty: 1,
    category: "boys",
  },
  {
    id: "60",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/s/0/y/4-5-years-a3-avacub-original-imah5ayyqz9986ba.jpeg?q=70",
    name: "Kilimoli",
    price: 491,
    description: "Boys Party(Festive) Track Pants T-shirt  (White)",
    qty: 1,
    category: "boys",
  },
];

module.exports = allData;
