const kidsproduct = [
  {
    id: "41",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/g/s/p/4-5-years-cpby0037-carrydreams-original-imagksy3yundy6bz.jpeg?q=70",
    name: "CHANDRIKA LIFESTYLE",
    price: 270,
    description: "Boys Party(Festive) T-shirt Trouser  (MEHENDI)",
    qty: 1,
    category: "boys",
  },
  {
    id: "42",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/t/4/y/6-7-years-ctcn01-cute-n-tight-original-imagsdfvnsfzrdp2.jpeg?q=70",
    name: "PY PINKYOU",
    price: 400,
    description: "Boys Casual Sweatshirt Track Pants  (Black)",
    qty: 1,
    category: "boys",
  },
  {
    id: "43",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shopsy-kids-apparel-combo/z/k/1/1-2-years-cpby0032-shopsy-chandrika-lifestyle-original-imagkrv3y2b7gprs.jpeg?q=70",
    name: "CHANDRIKA LIFESTYLE",
    price: 799,
    description: "Boys Casual Pants (Black)",
    qty: 1,
    category: "boys",
  },
  {
    id: "44",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/k/k/q/7-8-years-black-open-denim-blue-bold-born-original-imah375yrhgcwdeg.jpeg?q=70",
    name: "Bold Born",
    price: 499,
    description: "Boys Party(Festive) Shirt Jacket, Jeans (Blue)",
    qty: 1,
    category: "boys",
  },
  {
    id: "45",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/u/f/j/4-5-years-f1aa-lxri-original-imagpzyrgzrhrwg4.jpeg?q=70",
    name: "Lxri",
    price: 799,
    description: "Boys Party(Festive) Shirt Pant, Waistcoat  (Green)",
    qty: 1,
    category: "boys",
  },
  {
    id: "46",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/m/a/l/6-7-years-babushona636-yellow-30-babushona-original-imah3fgfjcsvg6qf.jpeg?q=70",
    name: "BABUSHONA",
    price: 699,
    description: "Boys Party(Festive) Track Pants Shirt  (Yellow)",
    qty: 1,
    category: "boys",
  },
  {
    id: "47",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/x/b/r/2-3-years-sp-6-year-grey-ultrina-original-imagqfucnktutw7c.jpeg?q=70",
    name: "ULTRINA",
    price: 369,
    description:
      "Boys Party(Festive) Shirt Pant, Bow Tie, Suspenders  (SKY BLUE)",
    qty: 1,
    category: "boys",
  },
  {
    id: "48",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shopsy-kid-costume-wear/x/t/b/72-4-5-years-cpby001-shopsy-pol-chandrika-lifestyle-84-original-imaghh3xtw63gqmm.jpeg?q=70",
    name: "ULTRINA",
    price: 325,
    description: "Chandrika Police Dress",
    qty: 1,
    category: "boys",
  },
  {
    id: "49",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/p/i/v/11-12-years-denc01-druzzee-original-imagwnkr3rjg8ags.jpeg?q=70",
    name: "DRUZZEE",
    price: 270,
    description: "Boys Casual T-shirt Track Pants  (Navy)",
    qty: 1,
    category: "boys",
  },
  {
    id: "50",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kid-costume-wear/z/9/p/2-3-years-military-costume-for-kids-kenim-fashion-original-imagvn5t3ugyq6vb.jpeg?q=70",
    name: "DRUZZEE",
    price: 270,
    description: "Chandrika Army Dress",
    qty: 1,
    category: "boys",
  },
  {
    id: "51",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/u/5/m/7-8-years-phd-go-berry-original-imah2mfv4rrcyywc.jpeg?q=70",
    name: "Go Berry",
    price: 644,
    description: "Boys Party(Festive) Shirt Pant  (YELLOW)",
    qty: 1,
    category: "boys",
  },
  {
    id: "52",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/x/y/j/1-2-years-trm-ttp-130-trampoline-original-imah5vsugnv3p7gf.jpeg?q=70",
    name: "Trampoline",
    price: 747,
    description: "Boys Casual T-shirt Track Pants  (Black, Blue)",
    qty: 1,
    category: "boys",
  },
  {
    id: "53",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/b/z/z/7-8-years-55-coat-go-berry-original-imah2m2f9en4qmae.jpeg?q=70",
    name: "Go Berry",
    price: 489,
    description: "Boys Party(Festive) Shirt Pant  (BLUE)",
    qty: 1,
    category: "boys",
  },
  {
    id: "54",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/g/v/9/3-4-years-army-printed-track-pant-t-shirt-set-for-boys-6-dollico-original-imahy9mjeeugrfhb.jpeg?q=70",
    name: "Kilimoli",
    price: 491,
    description: "Boys Party(Festive) Track Pants T-shirt  (White)",
    qty: 1,
    category: "boys",
  },
  {
    id: "55",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/k/x/o/4-5-years-open-black-double-pocket-blue-good-doo-apparel-s-original-imaggf6ruaudv96m.jpeg?q=70",
    name: "Kilimoli",
    price: 491,
    description: "Boys Party(Festive) Track Pants T-shirt  (White)",
    qty: 1,
    category: "boys",
  },
  {
    id: "56",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/m/u/p/3-4-years-dior-hood-red-mini-tikes-original-imah2guyvksrru6s.jpeg?q=70",
    name: "Kilimoli",
    price: 491,
    description: "Boys Party(Festive) Track Pants T-shirt  (White)",
    qty: 1,
    category: "boys",
  },
  {
    id: "57",
    img: "https://rukminim2.flixcart.com/image/612/612/kqgyhe80/kids-apparel-combo/s/l/j/12-13-years-3-pc-320-blue-zolario-original-imag4h9ycd5tsswg.jpeg?q=70",
    name: "Kilimoli",
    price: 491,
    description: "Boys Party(Festive) Track Pants T-shirt  (White)",
    qty: 1,
    category: "boys",
  },
  {
    id: "58",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/e/x/4/11-12-years-homtom-oversize-t-viskri-original-imagyp4dgfa2aes4.jpeg?q=70",
    name: "Kilimoli",
    price: 491,
    description: "Boys Party(Festive) Track Pants T-shirt  (White)",
    qty: 1,
    category: "boys",
  },
  {
    id: "59",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/u/l/m/8-9-years-boys-t-shirts-with-track-pant-ninos-dreams-original-imagxz4tyhfkfmup.jpeg?q=70",
    name: "Kilimoli",
    price: 491,
    description: "Boys Party(Festive) Track Pants T-shirt  (White)",
    qty: 1,
    category: "boys",
  },
  {
    id: "60",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/s/0/y/4-5-years-a3-avacub-original-imah5ayyqz9986ba.jpeg?q=70",
    name: "Kilimoli",
    price: 491,
    description: "Boys Party(Festive) Track Pants T-shirt  (White)",
    qty: 1,
    category: "boys",
  },
];

module.exports = kidsproduct;
