const product = [
  {
    id: "1",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/j/b/q/-original-imagy3k8xjfjhm4d.jpeg?q=70",
    name: "Puma",
    price: 679,
    description: "Ess Polo T-shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "2",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/j/b/q/-original-imagy3k8xjfjhm4d.jpeg?q=70",
    name: "Puma",
    price: 1034,
    description: "Men Medium Grey Solid ESS Jersey Pants",
    qty: 1,
    category: "Men",
  },
  {
    id: "3",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/e/b/t/m-t-26-1st-bukkl-original-imah3jdkrk8mmfsb.jpeg?q=70",
    name: "BUKKL",
    price: 289,
    description: "Men Printed Round Neck Pure Cotton White T-Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "4",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/k/v/m/xl-ts12-vebnor-original-imahfbc3yfnxp9j9.jpeg?q=70",
    name: "VeBNoR",
    price: 349,
    description: "Men Printed Round Neck Polyester Light Green T-Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "5",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/r/z/l/s-gucci-tshirt-sti-original-imahyyzs4kpgbfby.jpeg?q=70",
    name: "sti",
    price: 179,
    description: "Men Printed Round Neck Polyester White, Black T-Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "6",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/e/p/k/xl-sht02-ethvil-original-imagruyhhgztm4hj.jpeg?q=70",
    name: "Plorviz",
    price: 300,
    description: "Men Regular Fit Solid Mandarin Collar Casual Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "7",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/d/7/t/l-fms-182-fllseve-pop-wt-force-original-imah3qahwggdvdgm.jpeg?q=70",
    name: "Force",
    price: 339,
    description: "Men Regular Fit Solid Curved Collar Casual Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "8",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/e/y/h/m-towel-001-tallwalker-original-imaghct3gemhajg5.jpeg?q=70",
    name: "VASTRADO",
    price: 849,
    description: "Men Slim Fit Solid Lapel Collar Casual Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "9",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/5/7/v/3xl-formal-shirt-metronaut-original-imah2hqncjyyqead.jpeg?q=70",
    name: "VeBNoR ",
    price: 299,
    description:
      "Men Regular Fit Solid Button Down Collar Formal Shirt#JustHere",
    qty: 1,
    category: "Men",
  },
  {
    id: "10",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/2/s/e/s-rt121-s-line-original-imah3d3v9muqqeh4.jpeg?q=70",
    name: "S-Line",
    price: 299,
    description: "Men Regular Fit Printed Mandarin Collar Casual Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "11",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/r/c/4/s-jawan-one-nb-nicky-boy-original-imahfyq24y3hamvg.jpeg?q=70",
    name: "NB NICKY BOY",
    price: 249,
    description: "Men Printed Round Neck Cotton Blend Black T-Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "12",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/e/4/4/m-t599-whbl-eyebogler-original-imah46h9vwtyzkr8.jpeg?q=70",
    name: "EyeBogler",
    price: 269,
    description: "Men Checkered Hooded Neck Cotton Blend White T-Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "13",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/g/f/o/xxl-tblrnful-d158-tripr-original-imah545thkfje4sm.jpeg?q=70",
    name: "TRIPR",
    price: 259,
    description: "Men Solid V Neck Cotton Blend Black T-Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "14",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/g/a/t/l-hood-263-nasa-black-lewel-original-imaggeft89kbgsnh.jpeg?q=70",
    name: "LEWEL",
    price: 259,
    description: "Men Typography Hooded Neck Cotton Blend White, Black T-Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "15",
    img: "https://rukminim2.flixcart.com/image/612/612/l41n2q80/t-shirt/7/o/1/m-1jgrf-013-must-jugular-original-imagff7wwu2ptt9y.jpeg?q=70",
    name: "JUGULAR",
    price: 459,
    description: "Men Printed Round Neck Pure Cotton Yellow T-Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "16",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/7/v/0/l-t3-t2-autna-original-imagqphp3hj6vqdj.jpeg?q=70",
    name: "Autna",
    price: 659,
    description:
      "Men Colorblock V Neck Cotton Blend Maroon, Black, White T-Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "17",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/q/h/z/xl-jc23-polo-fs-olive-california-jump-cuts-original-imagvh7g6axuvyug.jpeg?q=70",
    name: "Jump Cuts",
    price: 999,
    description: "Men Printed Polo Neck Cotton Blend Dark Green T-Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "18",
    img: "https://rukminim2.flixcart.com/image/300/300/xif0q/t-shirt/i/q/b/m-white-black-pink-kroptee-original-imagkrk4gg4aatzm.jpeg?q=90",
    name: "Kroptee",
    price: 1199,
    description: "Men Colorblock Round Neck Pure Cotton Pink T-Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "19",
    img: "https://rukminim2.flixcart.com/image/300/300/xif0q/t-shirt/4/t/i/xxl-ausk0179-ausk-original-imagmffbcvcxu9gf.jpeg?q=90",
    name: "AUSK",
    price: 529,
    description:
      "Men Colorblock Polo Neck Cotton Blend Beige, Black, White T-Shirt",
    qty: 1,
    category: "Men",
  },
  {
    id: "20",
    img: "https://rukminim2.flixcart.com/image/612/612/kjhgzgw0-0/t-shirt/9/x/l/l-12329170-wrogn-original-imafzfb88duhmwz3.jpeg?q=70",
    name: "WROGN",
    price: 899,
    description: "Men Striped Round Neck Pure Cotton White T-Shirt",
    qty: 1,
    category: "Men",
  },
];

module.exports = product;
