const womenPrducts = [
  {
    id: "21",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/fabric/i/j/t/yes-2-m-unstitched-2-m-2-5-m-ti-1503-inithi-original-imah2axgyydpyhev.jpeg?q=70",
    name: "THIRA",
    price: 249,
    description: "Unstitched Crepe Salwar Suit Material Printed",
    qty: 1,
    category: "Women",
  },
  {
    id: "22",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/fabric/e/4/h/yes-2-m-unstitched-2-m-2-5-m-1576-laxmi-creation-original-imah29sfxaamgnna.jpeg?q=70",
    name: "THIRA",
    price: 249,
    description: "Unstitched Crepe Salwar Suit Material Printed",
    qty: 1,
    category: "Women",
  },
  {
    id: "23",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/fabric/5/z/t/yes-2-m-unstitched-2-m-2-5-m-ti-1567-inithi-original-imah2axgsa5vcg3y.jpeg?q=70",
    name: "THIRA",
    price: 249,
    description: "Unstitched Crepe Salwar Suit Material Printed",
    qty: 1,
    category: "Women",
  },
  {
    id: "24",
    img: "https://rukminim2.flixcart.com/image/612/612/l51d30w0/dress/n/g/n/xxl-d515-dress-s-starword-original-imagfsw6ynqpje7f.jpeg?q=70",
    name: "starword",
    price: 379,
    description: "Women Pleated Blue Dress",
    qty: 1,
    category: "Women",
  },
  {
    id: "25",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/dress/d/a/e/xl-f-188-190-sumertex-original-imagj3p5fhvvtcmt.jpeg?q=70",
    name: "METRONAUT",
    price: 319,
    description: "Women Fit and Flare Maroon Dress",
    qty: 1,
    category: "Women",
  },
  {
    id: "26",
    img: "https://rukminim2.flixcart.com/image/612/612/l1pc3gw0/dress/x/w/n/l-159-167-sumertex-original-imagd7hzdg2zzyau.jpeg?q=70",
    name: "SUMERTEX",
    price: 999,
    description: "Women Fit and Flare Brown Dress",
    qty: 1,
    category: "Women",
  },

  {
    id: "27",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/dress/r/j/u/m-dresses-lakshya-fashion-mart-original-imah2wymga5bfghz.jpeg?q=70",
    name: "Lakshya Fashion Mart",
    price: 239,
    description: "Women Fit and Flare Multicolor Dress",
    qty: 1,
    category: "Women",
  },
  {
    id: "28",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/dress/i/d/r/6xl-velvet-f-44-garima-fashion-original-imagnhzwtzpwufut.jpeg?q=70",
    name: "Garima Fashion",
    price: 3289,
    description: "Women Fit and Flare Maroon Dress",
    qty: 1,
    category: "Women",
  },
  {
    id: "29",
    img: "https://rukminim2.flixcart.com/image/612/612/k62i5jk0/dress/x/n/k/xl-fr-6022-gorangani-original-imafkyczeq7qvkzf.jpeg?q=70",
    name: "maruti fab",
    price: 7289,
    description: "Women Fit and Flare Black, Beige, Brown Dress",
    qty: 1,
    category: "Women",
  },
  {
    id: "30",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/dress/x/b/8/l-131923901-vero-moda-original-imagu8t6ymysp2r9.jpeg?q=70",
    name: "VERO MODA",
    price: 4299,
    description: "Women Fit and Flare Black Dress",
    qty: 1,
    category: "Women",
  },
  {
    id: "31",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/dress/b/0/u/s-rr-403-emb-frock-lozzby-original-imaghkupbfdtu5yk.jpeg?q=70",
    name: "BRIGHT WORLD",
    price: 399,
    description: "Women Ethnic Dress Black Dress",
    qty: 1,
    category: "Women",
  },
  {
    id: "32",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/dress/9/b/2/m-flared-dress-iqra-enterprise-original-imah28hguqqnbxpa.jpeg?q=70",
    name: "IQRA ENTERPRISE",
    price: 3909,
    description: "Women Fit and Flare Green Dress",
    qty: 1,
    category: "Women",
  },
  {
    id: "33",
    img: "https://rukminim2.flixcart.com/image/612/612/kjg1jm80-0/kurta/u/j/v/m-frock-10-gg-fashion-original-imafzy9tdxugehbe.jpeg?q=70",
    name: "Jashudi Style",
    price: 403,
    description: "Women A-line Black Dress",
    qty: 1,
    category: "Women",
  },
  {
    id: "34",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/dress/i/w/v/m-shirt-dress-black-plain-klart-original-imah4ebzhfvvegq6.jpeg?q=70",
    name: "KLART",
    price: 403,
    description: "Women Shirt Black Dress",
    qty: 1,
    category: "Women",
  },
  {
    id: "35",
    img: "https://rukminim2.flixcart.com/image/612/612/l1jmc280/dress/n/h/e/l-168-176-sumertex-original-imagd3a6zhayhszx.jpeg?q=70",
    name: "SUMERTEX",
    price: 807,
    description: "Women Fit and Flare Green Dress",
    qty: 1,
    category: "Women",
  },
  {
    id: "36",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/dress/l/n/e/m-women-s-crepe-knee-length-frock-dress-nyty20-original-imahfhvzgqqf3gsw.jpeg?q=70",
    name: "NYTY20",
    price: 535,
    description: "Women Fit and Flare Black Dress",
    qty: 1,
    category: "Women",
  },

  {
    id: "37",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/fabric/4/z/u/yes-2-m-unstitched-2-10m-jsg1618-simplyenthic-original-imagw9f4gy7z8epm.jpeg?q=70",
    name: "SIMPLYENTHIC",
    price: 279,
    description: "Unstitched Crepe Kurta & Churidar Material Printed",
    qty: 1,
    category: "Women",
  },
  {
    id: "38",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/fabric/n/k/x/yes-2-2-m-unstitched-2-10m-jsg1396-simplyethnic-original-imahftgdq49fpzxe.jpeg?q=70",
    name: "SIMPLYENTHIC",
    price: 674,
    description: "Unstitched Crepe Kurta & Churidar Material Printed",
    qty: 1,
    category: "Women",
  },
  {
    id: "39",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/fabric/r/e/6/yes-2-2-m-unstitched-2-m-2-5-m-free-7777888-amaaya-fashion-original-imah2txkhezsvmve.jpeg?q=70",
    name: "amaaya fashion",
    price: 674,
    description: "Unstitched Crepe Salwar Suit Material Printed",
    qty: 1,
    category: "Women",
  },

  {
    id: "40",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/jacket/f/b/v/s-1-no-lady-jacket-printcorners-original-imah4n8q6efczndg.jpeg?q=70",
    name: "printcorners",
    price: 674,
    description: "Women Solid Leather Jacket",
    qty: 1,
    category: "Women",
  },
];

module.exports = womenPrducts;
